zuul:
  prefix: /api/v1
  ignoredServices: '*'
  routes:
    activity-service:
       path: /activities/**
       url: http://activity-service:8090
    task-manager:
       path: /tasks/**
       url: http://task-manager:8092
    graph-service:
       path: /graph/**
       url: http://graph-service:8095
    user-service:
       path: /users/**
       url: http://user-service:8098
    api-gateway:
       path: /gateway/**
       url: http://api-gateway:8080
ribbon:
  eureka:
    enabled: true
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    fetchRegistry: true
